# Generated by Django 5.0.3 on 2024-03-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_setting_setting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='photo',
            new_name='image',
        ),
    ]
